print("xxxxxxxxxxxxxxx")
print("    W Shop")
print("xxxxxxxxxxxxxxx")
print("Whey apple x 2  :  50    Thb")
print("Whey Choc  x 5  :  125   Thb")
print("Orange     x 1  :  20    Thb")
print("Milk       x 5  :  50    Thb")
print("Donut      x 3  :  70    Thb")
print("Car        x 1  :  1,000 Thb")
print("Bottle     x 2  :  10    Thb")
print("Bear       x 1  :  100   Thb")
print("xxxxxxxxxxxxxxx")
print("total           :  1,425 Thb")